-- 코드를 입력하세요

SELECT FLAVOR -- SUM(TOTAL_ORDER + JULY_ORDER)
FROM FIRST_HALF 
LEFT JOIN (
    SELECT FLAVOR AS FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS ORDER_JULY
USING (FLAVOR)
GROUP BY FIRST_HALF.FLAVOR
ORDER BY SUM(TOTAL_ORDER + JULY_ORDER) DESC
LIMIT 3;